services:
  db:
    image: postgres
    container_name: dart_scoreboard_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1234
    volumes:
      - db:/var/lib/postgresql/data 
 
volumes:
  db: