name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run lint
      - run: npm run build
  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'
      steps:
        - uses: docker/setup-buildx-action@v1
        - uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build Docker image
          run: docker build -t mxwnk/dart-scoreboard:latest .
        - name: Push Docker image
          run: docker push mxwnk/dart-scoreboard:latest
